---
title: 'DATA 605: Assignment'
output: html_document
---
* Question: 1.1

Write R markdown script to compute ATA and ATb. 

```{r}

# A matric of A, b and X

A <- matrix(data=c(1, 0, 1, 1, 1, 3, 1, 4), nrow=4, byrow=TRUE)    

A

b <- matrix(data=c(0, 8, 8,20), nrow=4)
b


X <- matrix(data=c("x1", "x2"), nrow=2)
X


ATA <- A%*%t(A)

ATA


ATb <- t(A)%*%b

ATb
```

* Question: 1.2

Solve for x in R using the above two computed matrices

```{R}

qr.solve(A,b)

```

* Question: 1.3

Instead of b = [0;8;8;20], start with p = [1;5;13;17] 

```{R}
p <- matrix(data=c(1, 5, 13,17), nrow=4)
p

qr.solve(A,p)

```

* Question: 1.4

Show that the error e = b ??? p = [???1;3;???5;3]

```{R}
e <- b-p
e

```


* Question: 2

Consider the modi???ed auto-mpg data (obtained from the UC Irvine Machine Learning dataset). This dataset contains 5 columns: displacement, horsepower, weight, acceleration, mpg. We are going to model mpg as a function of the other four variables.


```{R}
#Read the data from uci.edu website

car_data <- read.csv("http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data", sep = "", header = F)

head(car_data) # Glipmse of the dataset before renaming?

colnames(car_data)[1] <- "mpg"
colnames(car_data)[2] <- "cylinders"
colnames(car_data)[3] <- "displacement"
colnames(car_data)[4] <- "horsepower"
colnames(car_data)[5] <- "weight"
colnames(car_data)[6] <- "acceleration"
colnames(car_data)[7] <- "model_year"
colnames(car_data)[8] <- "origin"
colnames(car_data)[9] <- "car_name"

head(car_data) # After renaming

# Subsetting the requirred dataset

auto_mpg <- subset(car_data, select=c(displacement,horsepower,weight, acceleration, mpg))
head(auto_mpg)

```


Write an R markdown script that takes in the auto-mpg data, extracts an A matrix from the ???rst 4 columns and b vector from the ???fth (mpg) column. Using the least squares approach, your code should compute the best ???tting solution. That is, ???nd the best ???tting equation that expresses mpg in terms of the other 4 variables. Finally, calculate the ???tting error between the predicted mpg of your model and the actual mpg. Your script should be able to load in the 5 column data set, extract A and b, and perform the rest of the calculations. Please have adequate comments in your code to make it easy to follow your work.


```{R}
suppressMessages(library(ggplot2)) #Load library and suppress warning message

fit <- lm(mpg ~ displacement+horsepower+weight+acceleration, data = auto_mpg) #Linear regression

stepwise <- step(fit, direction = "both") #selecting best model
summary(stepwise) # Summary of the best model with P-value less than 0.5

residual = data.frame(Fitted = fitted(stepwise), #Fitting Residual with Original dataset.
Residuals = resid(stepwise), Treatment = auto_mpg$mpg)
ggplot(residual, aes(Fitted, Residuals, colour = Treatment)) + geom_point() # Plot showing residual with fitted 

```